"""Generate a tool reference from public SDK introspection; CI checks it for drift."""

from __future__ import annotations

import argparse
import asyncio
import os
from pathlib import Path
from tempfile import TemporaryDirectory


async def render() -> str:
    from swissdatamcp.server import mcp

    tools = await mcp.list_tools()
    lines = [
        "# Tool reference", "",
        "Generated by `python scripts/generate_tool_reference.py`. Do not edit by hand.", "",
        "Tool annotations describe possible effects; they do not enforce permissions.", "",
    ]
    for tool in sorted(tools, key=lambda item: item.name):
        hint = tool.annotations
        effects = "Reads data" if hint.read_only_hint else "May write local files or tables"
        if hint.open_world_hint:
            effects += "; may access public network sources"
        if hint.destructive_hint:
            effects += "; may replace or remove existing local state"
        lines.extend([f"## `{tool.name}`", "", tool.description or "", "", effects + ".", ""])
        required = set(tool.input_schema.get("required", []))
        params = tool.input_schema.get("properties", {})
        if params:
            lines.extend(["| Parameter | Required | Default |", "| --- | --- | --- |"])
            for name, schema in params.items():
                default = repr(schema["default"]) if "default" in schema else "—"
                lines.append(f"| `{name}` | {'Yes' if name in required else 'No'} | `{default}` |")
            lines.append("")
        else:
            lines.extend(["No parameters.", ""])
    return "\n".join(line.rstrip() for line in lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    with TemporaryDirectory(prefix="swissdatamcp-docs-") as workspace:
        os.environ["SWISSDATAMCP_HOME"] = workspace
        result = asyncio.run(render())
    path = Path(__file__).resolve().parents[1] / "docs" / "tools.md"
    if args.check:
        if not path.exists() or path.read_text(encoding="utf-8") != result:
            raise SystemExit("Tool reference is stale. Run python scripts/generate_tool_reference.py.")
    else:
        path.write_text(result, encoding="utf-8")


if __name__ == "__main__":
    main()
